image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &

build_script:
  - sudo apt-get install chromium-browser=88.0.4324.104
  - chmod +x gradlew
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации